apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{TEAM_NAME}}-bot-{{BOT_UUID}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{TEAM_NAME}}-bot-{{BOT_UUID}}
  template:
    metadata:
      labels:
        app: {{TEAM_NAME}}-bot-{{BOT_UUID}}
    spec:
      containers:
      - name: {{TEAM_NAME}}-bot
        image: us-east4-docker.pkg.dev/pokerai-417521/{{TEAM_NAME}}/pokerbot:latest
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: "1"
            memory: "1.9Gi"
          requests:
            cpu: "0.5"
            memory: "1.9Gi"