apiVersion: batch/v1
kind: Job
metadata:
  name: engine-{{MATCH_ID}}
spec:
  ttlSecondsAfterFinished: 15
  template:
    spec:
      initContainers:
      - name: wait-for-bot1
        image: busybox
        command: ['sh', '-c', 'until nc -z {{TEAM1}}-bot-service-{{BOT1_UUID}} 50051; do echo waiting for bot1; sleep 2; done;']
      - name: wait-for-bot2
        image: busybox
        command: ['sh', '-c', 'until nc -z {{TEAM2}}-bot-service-{{BOT2_UUID}} 50051; do echo waiting for bot2; sleep 2; done;']
      containers:
      - name: engine
        image: us-east4-docker.pkg.dev/pokerai-417521/cmu-dsc/engine:latest
        env:
        - name: PLAYER_1_NAME
          value: {{TEAM1}}
        - name: PLAYER_2_NAME
          value: {{TEAM2}}
        - name: PLAYER_1_DNS
          value: {{TEAM1}}-bot-service-{{BOT1_UUID}}:50051
        - name: PLAYER_2_DNS
          value: {{TEAM2}}-bot-service-{{BOT2_UUID}}:50051
        - name: MATCH_ID
          value: "{{MATCH_ID}}"
        - name: BUCKET_NAME
          value: poker-ai-blobs
        - name: DATASET_ID
          value: pokerai-417521.poker_dataset
        - name: INSTANCE_CONNECTION_NAME
          value: pokerai-417521:us-east4:pokerai-sql
        - name: DB_USER
          value: root
        - name: DB_PASS
          value: .YFHUMhVJry#'SDt
        - name: DB_NAME
          value: pokerai-db
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: logs
          mountPath: /usr/src/app/logs
      restartPolicy: OnFailure
      volumes:
      - name: logs
        emptyDir: {}
