version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pokerbots_db
    restart: always
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DB: pokerbots
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pokerbots_network

volumes:
  postgres_data:

networks:
  pokerbots_network:
    driver: bridge
