name: Deploy ELO Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'elo-function/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Zip function
      run: |
        cd elo-function
        zip -r ../elo_function.zip .
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1
    - name: Upload to S3 and update Lambda
      run: |
        aws s3 cp elo_function.zip s3://cmu-poker-lambdas/elo_function.zip
        aws lambda update-function-code --function-name elo-function --s3-bucket cmu-poker-lambdas --s3-key elo_function.zip